<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTigoliw\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTigoliw/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTigoliw.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTigoliw\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTigoliw\appProdProjectContainer([
    'container.build_hash' => 'Tigoliw',
    'container.build_id' => 'a3ab5bb2',
    'container.build_time' => 1616175457,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTigoliw');
